Repository SOPT-29th-Joint-Seminar-8/NaverBlog-AOS, pull requests merged in 2021-11, with the labels that each got.

#4 #3 [FEAT] : MainActivity BottomNavigation Write Icon Insertion
  app/src/main/java/co/kr/naverblog_andoid/view/main/MainActivity.kt
  app/src/main/java/co/kr/naverblog_andoid/view/main/alarm/AlarmFragment.kt
  app/src/main/java/co/kr/naverblog_andoid/view/main/profile/ProfileFragment.kt
  app/src/main/java/co/kr/naverblog_andoid/view/main/recommend/RecommendFragment.kt
  app/src/main/java/co/kr/naverblog_andoid/view/main/write/WriteFragment.kt
  app/src/main/res/drawable-hdpi/btn_write.png
  app/src/main/res/drawable-mdpi/btn_write.png
  app/src/main/res/drawable-xhdpi/btn_write.png
  app/src/main/res/drawable-xxhdpi/btn_write.png
  app/src/main/res/drawable-xxxhdpi/btn_write.png
  app/src/main/res/drawable/shape_bottom_navigation_write.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_alarm.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_recommend.xml
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/values/strings.xml
Labels: feat

#12 #11 [FEAT] : CommentActivity GoUp Button Click Event 구현
  app/src/main/java/co/kr/naverblog_andoid/view/comment/CommentActivity.kt
  app/src/main/res/layout/activity_comment.xml
Labels: feat, SeungHyeon

#13 Feat/10 comment activity
  app/src/main/java/co/kr/naverblog_andoid/view/comment/CommentActivity.kt
  app/src/main/res/layout/activity_comment.xml
Labels: feat, SeungHyeon

#14 Feat/9 comment activity
  app/src/main/java/co/kr/naverblog_andoid/adapter/CommentAdapter.kt
  app/src/main/java/co/kr/naverblog_andoid/adapter/CommentFeedbackAdapter.kt
  app/src/main/java/co/kr/naverblog_andoid/data/CommentData.kt
  app/src/main/java/co/kr/naverblog_andoid/data/CommentFeedbackData.kt
  app/src/main/java/co/kr/naverblog_andoid/view/comment/CommentActivity.kt
  app/src/main/res/drawable-hdpi/btn_goup.png
  app/src/main/res/drawable-hdpi/btn_owner.png
  app/src/main/res/drawable-mdpi/btn_goup.png
  app/src/main/res/drawable-mdpi/btn_owner.png
  app/src/main/res/drawable-xhdpi/btn_goup.png
  app/src/main/res/drawable-xhdpi/btn_owner.png
  app/src/main/res/drawable-xxhdpi/btn_goup.png
  app/src/main/res/drawable-xxhdpi/btn_owner.png
  app/src/main/res/drawable-xxxhdpi/btn_goup.png
  app/src/main/res/drawable-xxxhdpi/btn_owner.png
  app/src/main/res/drawable/selector_comment_button.xml
  app/src/main/res/drawable/selector_comment_heart.xml
  app/src/main/res/drawable/shape_full_rectangle_gray.xml
  app/src/main/res/drawable/shape_full_rectangle_green.xml
  app/src/main/res/layout/activity_comment.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/layout/item_comment_feedback.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feat, SeungHyeon

#17 #16[FEAT]:FeedFragment item click event구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/co/kr/naverblog_andoid/adapter/FeedAdapter.kt
  app/src/main/java/co/kr/naverblog_andoid/data/FeedData.kt
  app/src/main/java/co/kr/naverblog_andoid/view/main/feed/FeedFragment.kt
Labels: feat, HyeBin
